language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="pydjango.settings.travis"

services:
  - postgresql

script:
  - export SECRET_KEY=SECRET_KEY
  - python manage.py test