language: python
python:
  - '3.8.5'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="pydjango.settings.travis"

services:
  - postgresql