language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - master

env:
  - DJANGO_SETTINGS_MODULE="pydjango.settings.travis"

services:
  - postgresql

script:
  - python manage.py test